use_default_settings: true

search:
  formats:
    - html
    - json

server:
  base_url: "https://mimetista-searxng.onrender.com"
  secret_key: "MimetistaAI-9f7K2x4P8m6Q"
  limiter: false
  public_instance: false
